menu:
    Home: /
    英語サイト: https://www.daigotanaka.com/en
    Archive: /archives/

title: Daigo Tanaka
keywords: blog, english, japanese
description: Daigo Tanaka's essays and blog
# Copyright Infomation
startyear: 2009
