menu:
    Home: /
    Archive: /archives/
    About: "/about/"

title: Daigo Tanaka
keywords: blog, english, japanese
description: Daigo Tanaka's essays and blog
# Copyright Infomation
startyear: 2009
